### ISSUE TITLE
Epic: Make `NexusMods.*` Packages available for External Developers

### ISSUE THREAD

**Issue by Sewer56** [Nexus-Mods/NexusMods.App#104]
# User story

**As a** developer working on my own software.  
**I want to** write programs that understands the data and entity model.  
**So that** I can write software that integrates with the Nexus Mods App.  

[This also applies to Extensions]

## Requirements
These will be replaced with issues down the road.

- Package `NexusMods.FileExtractor` as NuGet Packages.  
  - [Setup Basic NuGet Package Details.](https://github.com/Nexus-Mods/NexusMods.App/issues/105)
  - Publish NuGet Packages during CI.  
  
- Write `Getting Started` document for the `NexusMods.*` APIs.  

## Additional Details

Not ready/completion backlogged until end of MVP.

**Comment by erri120** [comment]
As part of #148, I want to use `NexusMods.Paths`, now that #168 is merged, in GameFinder for Wine/Proton/Bottles support.

It might be worth setting up a nightly build feed, similar to #155 but for NuGet. [Avalonia](https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed) does this as well and is probably a better than using nuget.org, since we're still in early development.

**Comment by Sewer56** [comment]
We're not yet publishing packages anywhere yet; I'm not sure if this is appropriate for closing.

**Comment by halgari** [comment]
you're right, I was confused with the work we did on the fomod installer
