### ISSUE TITLE
Change `TreeDataGridSource` creation to use XAML based `DataTemplate`

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#1049]
- See bottom part of [this TreeDataGrid doc](https://github.com/AvaloniaUI/Avalonia.Controls.TreeDataGrid/blob/master/docs/column-types.md)
- You can still use a custom view by adding it in the Xaml DataTemplate, then setting the VM for it in the TreeDataGridSource creation.
- Move CreateTreeSource in the ViewModel instead of codebehind, as done in the TreeDataGrid documentation and samples.

**Comment by Sewer56** [comment]
Closed on behalf of @Al12rs and @Sewer56 (me)

- We timeboxed it
- We debugged it
- Unfortunately it doesn't work
- Virtualization is broken so columns don't properly update while scrolling
- Seems to an upstream bug (although not 100% confirmed, maybe works with `CompiledBinding`, but doesn't work with `Binding`)
- We tried to be as close to examples as possible too.
- And even then, if it worked, we had ergonomic issues. e.g. XAML Editor can't tell if a named resource is used because it's only referenced in related code behind.
