### ISSUE TITLE
Garbage Collection - Delete Mod

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#1186]
Users will need the ability to be able to delete mods. 

This will be because of wanting to free up disk space or because they no longer want to see that mod anymore. 

Does deletion mean completely remove from disk? 
Should the app facilitate disk delete? 
Are we going to be able to rollback a disk delete? By downloading it again?
How will diagnostics work with deleted files? 

- [ ] https://github.com/Nexus-Mods/NexusMods.App/issues/1174

**Comment by LukeNexusMods** [comment]
Laurence has a few questions on this one.

What is the planned process for this, will it go into a recycle bin, does it affect backups. How should the deletions be communicated to the users, this largely depends on how this item will work. 

@halgari

**Comment by Al12rs** [comment]
## Garbage collection meeting notes (@Al12rs @Sewer56):
Just some relevant notes of things that might be handy to remember down the line from a meeting on this:

- We could do deletion on-line, immediately on user deletion of some entities, in which case we would know what hashes need to be deleted
	- Risk of other operations interfering (other packing and extracting operations)
- Offline operation would compare all the hashes in the NX archives headers with all the hashes referenced in the DB, and delete any hashes that are not referenced. Proper GC operation.
	- No need to keep ToBeDeleted state in DB since the hashes are stored in the nx headers
	- Deleting data offline might be worse user experience because users expect data to be freed immediately, not on restart.
- Limiting nx archive sizes to around 1gb could help reduce overhead when deleting files because it is bottlenecked by disk stpeed and the operation needs to read and write the entire archive.
- As an optimization for the future we could compact existing smaller (<100Mb) archives into new ones on new archive creation, by appending the already compacted blocks to new archives that share one or more files.
	- This can be handled fine in the future, as compacting on new mod download would sort out the fragmentation problem, even if already very fragmented.
