### ISSUE TITLE
Why not hardlinks instead of copies for backup

### ISSUE THREAD

**Issue by jthoward64** [Nexus-Mods/NexusMods.App#1350]
# Improvement

## Currently 

Right now the app requires making a complete copy of the game when backing up, causing massive storage overhead

## We want

Less storage overhead

## Design

Why not use hardlinks to backup game files instead? The only risk I can see with this is mutation of the hard-linked files, but I don't know of many mods that mutate base game files because they would get overwritten with an update anyways. However, if this is a concern the solution could just be to have a white/blacklist for what files are allowed to be hardlinked vs copied for backups. For example you can be pretty confident that no Bethesda mod will be mutating BSA files

P.S. I am coming at this from a Linux perspective, and it is possible there is something I'm missing from the Windows side of things

**Comment by halgari** [comment]
We did some analysis early on, and there are numerous drawbacks to using hardlinks, many of which are mentioned here: https://github.com/Nexus-Mods/NexusMods.App/blob/main/docs/misc/ComparisonOfFileManagementSystems.md

Mostly it comes down to not knowing if the files changed, and not being able to revert the files in situations where they are utterly destroyed by a Steam update or other such operation. We're looking into options for opting-out of backing up certain files, but the recommended approach will be to back up everything so that an accidental file modification by the user, or Steam doesn't wipe an entire loadout.

**Comment by Sewer56** [comment]
I'll save it to @halgari for a more detailed explanation, of they feel like it.
Edit: They already did by time I posted.

Been suggested before, even by myself a year ago in the beginning. Main caveat is though we don't know when/if someone will make a modding tool that modifies a new type of file in place. As working by directly editing files (for better or worse) is a practice in some communities, unfortunately endulge in.

In an ideal world, we would have a Copy on Write Filesystem like Btrfs more readily available, but unfortunately we don't really live in a world where that is possible, especially given since most users will be locked to NTFS.

**Comment by jthoward64** [comment]
Good to know, thanks!

P.S. Yeah CoW snapshot are the real answer, but oh well

**Comment by halgari** [comment]
On the subject of COW though @jthoward64 Windows 11 is getting ReFS "soon", and many linux distros have a COW system. At some point we'll likely sit down and find a way to integrate that, so instead of copying/compressing files, we'll snapshot the folder, then use that as our "Base image" in the situation where we need to roll back. It would need to be prototyped but I think it would actually be fairly simple to implement.
