### ISSUE TITLE
OAuth doesn't show the instruction overlay

### ISSUE THREAD

**Issue by halgari** [Nexus-Mods/NexusMods.App#1379]
# Bug Report

While testing I realized we somehow lost the OAuth instructions overlay.

**Comment by erri120** [comment]
I forgot we even had this overlay, it has been disabled for a long time.

**Comment by erri120** [comment]
We added the overlay in #223:

https://github.com/Nexus-Mods/NexusMods.App/pull/223/files#diff-52f87ee790431767becf9a057f0a9db243e1873df0c673d9c5dc0c0049997a34

#360 updated how this worked:

https://github.com/Nexus-Mods/NexusMods.App/blob/68cb7d3bb22a30711990c9b0abddb5a5eee8b32b/src/NexusMods.App.UI/Windows/MainWindowViewModel.cs

#500 broke the behavior:

https://github.com/Nexus-Mods/NexusMods.App/pull/500/files#diff-52f87ee790431767becf9a057f0a9db243e1873df0c673d9c5dc0c0049997a34

The issue is that `NexusLoginOverlayViewModel` runs code in the constructor that listens for login jobs. If we don't instantiate one instance of this class, the overlay never shows. Since this behavior is implicit, we removed usages to this VM because our IDE would show it as "unused".

**Comment by halgari** [comment]
Yeah, I fixed the DI issue and that didn't fix the issue for some reason. Going to look at it more today

**Comment by erri120** [comment]
Done in #1402.
