### ISSUE TITLE
Prevent apply action while the game is running

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/NexusMods.App#1442]
# User story

**As a** user

**I want to** be prevented from applying my changes while the game is running 

**So that** I don't hit permission issues or cause problems with my active game session 

## Requirements
_(Any other information related to but not covered by the story)_

## Design
_(Any designs required for this story)_

## DOD
_(Describe the expected behaviour from the users point of view. Create multiple DoD's if required to fully describe what should happen. Number each DoD)_

## Scenario 1
**Given** _______

**When** _______

**Then** _______

**Comment by erri120** [comment]
The apply button is hidden while the game is running. Isn't that enough?

**Comment by Al12rs** [comment]
Not if you make a change to the loadout while the game is running.
I'll fix this in my open PR.

**Comment by Al12rs** [comment]
So, I can disable the button while the game is running. 

This puts fourth another issue though:
If you toggle a mod while the game is running, the button will not show, as expected. Then when the game is closed though, the button will keep not being shown, because when the game is closed we do an ingest, and thus update the last applied state to our most recent loadout transaction. Problem is, we never did an apply of that transaction, so this is simply false.
