### ISSUE TITLE
Epic: Linux support

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#148]
# Epic

**NOTE for newcomers:** The App is already fully functioning on Linux. This includes both the CLI and the GUI. The issues linked below are specific Linux-related issues that still need to be worked on.

## Issues

- [x] #157
- [x] #164 
- [x] #149
- [x] #150
- [x] #151 
- [x] #179
- [x] #181
- [x] #168
- [x] #201
- [x] #285

**Comment by BloodyIron** [comment]
Does this mean it will/may have GUI aspects on Linux some day? :)

**Comment by erri120** [comment]
> Does this mean it will/may have GUI aspects on Linux some day? :)

We're using Avalonia, which is supported natively on Windows, Linux and macOS. Both the GUI and CLI versions of the App are fully functioning on Linux.

I daily drive Linux and deal with most of the Linux related details. Since this is a fresh codebase, we were able to start with a somewhat clean slate and have cross-platform support from the get-go. There are some minor implementation details left to be dealt with, as listed above in the issue, but almost all features are working on Linux.

**Comment by Sewer56** [comment]
Likewise, in the offchance I write some code that needs validation on Linux; I'll usually boot up into a VM and see how things go.  
So we do test on Linux actively; all in all.  

I will admit however, for the Nexus App, macOS is currently in a bit of a blind spot. Nobody's actively developing on that platform; and CI/CD is not currently running macOS (although we do have some macOS specific code).  Stuff on that end is mostly postponed as nobody on the team actively develops on a Mac machine and the amount of games you can run there is very, very small; due to lack of Wine and native ports being few and far between.

**Comment by BloodyIron** [comment]
Well I was more asking because from what I read (and maybe I misread) it looked like the Linux edition would be CLI. So yay! GUI and CLI stuff is both nice!
