### ISSUE TITLE
Sidebar design improvements

### ISSUE THREAD

**Issue by captainsandypants** [Nexus-Mods/NexusMods.App#1601]
Sidebar design improvements to give more space for sidebar buttons, simplify the UI, and improve active states.

Remove glow effect
Remove divider
Change active states
Change padding 
Change colours
Change transitions

[Figma link](https://www.figma.com/design/RGRSmIC4KoVlIosQB5YmQY/%F0%9F%93%B1%F0%9F%A7%B1-App-components?m=auto&node-id=971-5523&t=vTR45Pqi1V8KWQrh-1)

![Image](https://github.com/Nexus-Mods/NexusMods.App/assets/118466382/1a54a5a7-fe11-4549-bf38-eb1147beb316)

**Comment by Sewer56** [comment]
@captainsandypants 

Would it be much work to somehow indicate where the source of truth for the sidebar is?
Throughout designs, we now have multiple iterations of the bar. Some with old icon, some with glow & separator, etc.
It might become hard to keep track.

**Comment by insomnious** [comment]
It's a concern of mine as well as things get more complicated, I'm making a bit of a list with some UI related things that will help us long term, mainly from a docs and tidying point of view. This item is on there.

Specifically with the Spine, I would say that as soon as loadouts are up and running, we can move fully towards the final spine design. What we have now is a bit of a hybrid between the original and the end so that we can tick enough boxes for first release. At that point, we can clean up behind ourselves.
