### ISSUE TITLE
Simplify protocol handler

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#1677]
Currently, we register NXM links to open `NexusMods.App --protocol-invoke %u`. This has major downsides when it comes to Desktop Entries on Linux, which are files that tell the desktop environment about the program and how to handle protocols.

With this separate command, we need two desktop entry files, one for launching the application itself using `NexusMods.App` and one for dealing with NXM links using `NexusMods.App --protocol-invoke %u`.

It'd be much easier if we only have one way: `NexusMods.App %u`. With this approach, if we have a NXM link, then it will be the first argument. If we don't have a link, we get no argument and launch the UI normally.

**Comment by erri120** [comment]
Related to #1668.

**Comment by MattSturgeon** [comment]
This does simplify the .desktop files, but it feels strange to have the CLI vary across platforms.

Consider a user who has read `--help` (or usage examples) on one platform, who later goes on to use the app on another platform. They will be confused when their normal CLI usage doesn't work.

I guess this could be mitigated by having `--protocol-invoke` available on all platforms and treating `NexusMods.App %u` as an undocumented feature, but it'll still confuse anyone who references examples instead of docs.

IMO the CLI should be the same on all platforms: `--protocol-invoke` should be the documented approach, and a nxm URL being the first (only?) arg should imply `--protocol-invoke` on all platforms (either a documented behaviour or not).

**Comment by erri120** [comment]
> This does simplify the .desktop files, but it feels strange to have the CLI vary across platforms.
> 
> Consider a user who has read `--help` (or usage examples) on one platform, who later goes on to use the app on another platform. They will be confused when their normal CLI usage doesn't work.
> 
> I guess this could be mitigated by having `--protocol-invoke` available on all platforms and treating `NexusMods.App %u` as an undocumented feature, but it'll still confuse anyone who references examples instead of docs.
> 
> IMO the CLI should be the same on all platforms: `--protocol-invoke` should be the documented approach, and a nxm URL being the first (only?) arg should imply `--protocol-invoke` on all platforms (either a documented behaviour or not).

`--protocol-invoke` still always works and everywhere, using `NexusMods.App %u` where `%u` is a URI will do the same thing as `--protocol-invoke`.

**Comment by MattSturgeon** [comment]
> `--protocol-invoke` still always works and everywhere, using `NexusMods.App %u` where `%u` is a URI will do the same thing as `--protocol-invoke`.

That's good, at least the _documented_ CLI will be consistent cross-platform. This covers the mitigation:
> I guess this could be mitigated by having `--protocol-invoke` available on all platforms and treating `NexusMods.App %u` as an undocumented feature, but it'll still confuse anyone who references examples instead of docs.

I still think it'd be better if _everything_ was consistent cross-platform though, including the undocumented "first arg is a URI" scenario.

Or is this already the case and I'm misinterpreting https://github.com/Nexus-Mods/NexusMods.App/pull/1683#issuecomment-2188436364?
