### ISSUE TITLE
on linux my games dont come up (im using steam deck

### ISSUE THREAD

**Issue by purpleguy5728** [Nexus-Mods/NexusMods.App#1886]
# Bug Report

how do i fix this?

**Comment by Sewer56** [comment]
Currently we only show Stardew Valley and Cyberpunk 2077 if installed via Steam on Linux. Is that the case here?

**Comment by purpleguy5728** [comment]
oh i was looking to mod 
Five Nights at Freddy's: Security Breach and the long drive

**Comment by Sewer56** [comment]
Right now, this isn't possible with the App, sorry.

**Comment by purpleguy5728** [comment]
how do i mod the games on steam deck?

**Comment by Sewer56** [comment]
> how do i mod the games on steam deck?

It varies with the game.

Each game uses different modding tools/loaders etc. Mod managers usually expose easy to use UI around these games.

Since it varies on a per game basis, there is no definitive answer short of doing a bit of google searching. Generally speaking however, you can run most Windows tools in Wine/Proton.
