### ISSUE TITLE
Always use valid pipe target for CliWrap

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#1905]

**Comment by j-m-harris** [comment]
`xdg-open` launched from the app hangs on Ubuntu 24.

**Comment by Sewer56** [comment]
Re: Ubuntu

The issue only happens with the Steam snap. And nobody really uses Snap outside of Ubuntu, so  that's a piece of good news somewhat.

The official Steam deb and the apt package work fine.
I just wanted to check those too, after repro-ing on the Snap version; I'll be looking into this a bit more now.

**Comment by j-m-harris** [comment]
Does not appear to be specific to the deb or snap, but rather an instance of this problem: https://github.com/Tyrrrz/CliWrap/issues/145#issuecomment-1100680547

**Comment by Sewer56** [comment]
Ah okay. I did some more testing. And talked with @j-m-harris on the company Slack. (and he beat me to the response above)

Basically it boils down to this issue:
- https://github.com/Tyrrrz/CliWrap/issues/145#issuecomment-1100680547

So basically Steam, somewhere in startup is trying to write to `stderr`. It doesn't always do it for me, so sometimes it just worked, which led to me getting the wrong intiial assumption in https://github.com/Nexus-Mods/NexusMods.App/issues/1905#issuecomment-2302267955.

Basically, Steam's writing to `stderr` which has been nulled out in the failure case, and is not handling that gracefully; instead dying due to a broken pipe.

As for handling it, `PipeTarget.ToStream(Stream.Null)` as mentioned above is the play; so launched processes still get valid `stdout`/`stdin`/`stderr`. When we run a process with logging inside the App, we always redirect `stdout` and `stderr` to a file; therefore piping it to null by default is okay, as it'll still get overwritten in the logging case. 

When a user runs the App from CLI, they presumably don't also want the logs of any launched processes mixed with the actual App's stdout, therefore muting it by default should be reasonable behaviour.
