### ISSUE TITLE
GameFinder: AGameLocator will error if Steam Library has no App Manifests

### ISSUE THREAD

**Issue by Sewer56** [Nexus-Mods/NexusMods.App#193]
# Bug Report

## Summary

If you delete all games from a Steam Library folder such that there are no `appmanifest_*` files left, GameFinder will error with the following message:

```
While looking for <GAME_NAME>: Library folder <LIBRARY_PATH> does not contain any manifests
```

This error is currently silent to the user [only gets logged].  

This is an issue because an end user can legitimately reach this state by just transferring all games from one Steam Library folder to another.  

## Steps to reproduce

- Move all games from one library folder to another.

## What is the expected behaviour?

Error is suppressed, game finder can still find games present in other library folders.

**Comment by erri120** [comment]
I think this error is a bit deceptive and you have a different problem. GameFinder was designed to return every game it finds, as well as all errors it might encounter to help debugging. If one game has errors, GameFinder will not stop but continue with other games. Similarly, if one Steam library has errors, it will return an error but still look at other Steam libraries.

In this case, NMA logged all errors: https://github.com/Nexus-Mods/NexusMods.App/blob/61c39a627deda2277e9b339104d19721707a879c/src/NexusMods.StandardGameLocators/AGameLocator.cs#L32

Which originated from here: https://github.com/erri120/GameFinder/blob/a75ed5fe2f6abc9abd9566b9c355e2b711422ee0/src/GameFinder.StoreHandlers.Steam/SteamHandler.cs#L115

Your issue is that GameFinder didn't pick up on the new Steam library. This is, more often than not, an issue on Steam's side for not correctly updating your `libraryfolders.vdf` file. I'd suggest opening `C:\Program Files (x86)\Steam\steamapps\libraryfolders.vdf` and checking if all Steam libraries are in this file.

We can move this to the GameFinder repo if this error persists, but right now, NMA code works as intended.
