### ISSUE TITLE
Cleanly Integrate FOMOD XML support

### ISSUE THREAD

**Issue by halgari** [Nexus-Mods/NexusMods.App#198]
Based on Tannin's work, I think we're ready to move forward on integrating FOMOD support into the app. 

Use https://github.com/Nexus-Mods/NexusMods.App/tree/87-fomod-xml for reference. 

I'm not too keen on the idea of using git submodules here because they tend to be a rather brittle and we already have solid package management via nuget. 

Something we can fix in this prototype, is the converting of IModInstaller to async. Ideally mod installers should always be side-effect free. Any code that needs to perform IO should be moved into a IFileAnalyzer so that mod installation is a purely functional operation: you feed it mod info, it returns install info, with no side effects to the disk.  

Objectives:

* [x] Release the FOMOD XML library via Nuget 
* [x] Move the [analysis code](https://github.com/Nexus-Mods/NexusMods.App/compare/main...87-fomod-xml#diff-aa580f1cb2562c35f061663ab1b33aa224464a51bda267e2147c16a622ea533fR44-R63) into a `IFileAnalyzer` and cache the XML so we don't have to run extractors during the mod install
* [x] Remove the modifications to the API that were required by making IModInstaller async

For now, let's keep the FOMOD code as a black box, we shouldn't need to modify it to accomplish these goals, just write a package/publish script for the library code, and then import it into the app via Nuget.

**Comment by BellCubeDev** [comment]
If at all possible, a good way to go about installing installer-based archives might be to only extract the files you need at any given time—less disk IO and probably less install time. From how I've observed FOMODs in the wild, the file size difference between different install options can be quite large. Some things to keep in mind:

* Images should ideally be ready on-demand. It may be worth extracting all images referenced by the FOMOD installer and caching all of the images used in the current step. To present the installer ASAP, I'd:
  * Extract the mod image before we show the installer
  * Extract option images for each step in the background, prioritizing the earliest steps first
  * It may also be worth extracting the first step's images before showing the installer.
* Evaluating any conditions that don't make use of flags at the start and installing those files in the background may speed things up
* All files selected during the installer options should be installed _after_ the installer is closed (I'm not too familiar with how Nexus Mod App is going to handle this sort of thing, so this may well be a moot point)
* Breaking the IO theme here, game modules/extensions/whatevers that provide a game version could expose a version to `gameDependency` dependency type. Similarly, they might be able to expose some sort of "extender" version that could be used by the `foseDependency` dependency type.

I echo Tannin in that keeping `IModInstaller` synchronous seems like a bad idea; an async installer would allow more freedom for things like, well, an installer with user-facing options. `Task.fromResult` seems to handle things just fine for a synchronous installer. It may be worth inserting logic to allow both `Task` and `IEnumerable<AModFile>` as acceptable return values for `Install` rather than the proposed `Install` and `InstallSync`

**Comment by halgari** [comment]
> If at all possible, a good way to go about installing installer-based archives might be to only extract the files you need at any given time—less disk IO and probably less install time. From how I've observed FOMODs in the wild, the file size difference between different install options can be quite large. Some things to keep in mind:

This isn't always possible, infact it's not possible in any situation where the source archive is a 7z. This is because 7z is a SOLID archive meaning there's no way to jump directly to a specific file to extract it, in order to extract a file all the previous files in the archive have to be extracted enough to jump past them. We do have the facility to not write these unneeded files to disk, but not the ability to skip the CPU computation involved in uncompressing them.

**Comment by Sewer56** [comment]
Note: Not all .7z archives are SOLID, they are SOLID by default but they don't have to be. Point still stands nonetheless.

In any case; I gotta investigate this on Monday; see what ideas I can come up with. I haven't yet had a full dig through how this is currently integrated.

**Comment by Aragas** [comment]
In case this might be useful for parsing mod files from archives.
https://github.com/BUTR/BUTR.Site.NexusMods/blob/40d6c13956a4faa7afd074b0df67078b9aae5814/src/BUTR.Site.NexusMods.Server/Services/NexusModsInfo.cs#L45
This is start of code that uses HTTP Range to parse archives from NexusMods and extract specific data from specific files (Id property of SubModule.xml). It supports all archives and was battle-tested against every Bannerlord mod.
This still won't fix the SOLID issue, you'll need to potentially download the whole archive eventually tho.
