### ISSUE TITLE
Times and Dates are displaying future times

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#2207]
![Image](https://github.com/user-attachments/assets/5e65efa9-d012-45d0-bd2d-d21a3f16f71b)

Added times and dates appear far into the future on all pages that show times and dates.

**Comment by erri120** [comment]
I believe this is a result of some recent DB changes. Loading an old data store with a newer app version could cause this issue because we're storing and loading the dates differently. Not really a bug, you just have to reset your data store. It would be a bug if this issue also comes up with new data. Can you add a mod and check the dates?

**Comment by LukeNexusMods** [comment]
This from from a fresh install with no mods installed. I downloaded a collection and those were the dates and times it gave me.
