### ISSUE TITLE
Research and implement user/exception tracking

### ISSUE THREAD

**Issue by halgari** [Nexus-Mods/NexusMods.App#235]
# User story

As an: app developer
I want to: know what exceptions we're seeing in the app, and get generalized usage statistics

As an: app user
I want to: opt-into or out-of statistics gathering. 

## Requirements

* should allow tracking performance metrics, exceptions, and generalized usage
* must allow for opt-ing out by the user, ignore the UI for this for now, instead implement it as a config parameter
* include the app build SHA/version number in the metrics
* document if Vortex is opt-in or opt-out to metrics. 

## Design
We already have this in Vortex so start with that approach and see if we can replicate it in the app

**Comment by erri120** [comment]
Not sure what Vortex uses, but [OpenTelemetry](https://opentelemetry.io) has great [.NET](https://opentelemetry.io/docs/instrumentation/net/) implementations. The entire thing is vendor agnostic, so telemetry data can be exported to anything.

**Comment by erri120** [comment]
#333 is related.

**Comment by Aragas** [comment]
There's [OpenTelemetry.Exporter.InMemory](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Exporter.InMemory) that could be used to save tracing/metrics/logging data to some arbitrary format to be sent further, after an opt-in.
The data can explode in size tho if operations that are really common are traced

**Comment by erri120** [comment]
I've created a small test repository for OpenTelemetry: https://github.com/erri120/Telemetry.NET

It contains an example that goes over most features and explains how to use them. This is mostly about integrating OpenTelemetry into our codebase. I've provided some examples for services that collect the telemetry data, but that is likely an internal discussion for another time.

**Comment by erri120** [comment]
> Also take note that a DI aware approach is possible via `TracerProvider`. Here's a real in-use example. https://github.com/P3D-Legacy/P3D-Legacy-Server/blob/0add9bf72874fe435c16a06e289794a779366722/src/P3D.Legacy.Server.Client.P3D/P3DConnectionContextHandler.cs#LL61C6-L61C6

This [Slim Tracing](https://opentelemetry.io/docs/instrumentation/net/shim/) has multiple downsides:

1) You always need to register a `TracerProvider` even if you disabled telemetry. This hurts performance and complicates your setup code, since you're now always creating traces. Meanwhile, `ActivitySource.StartActivity` will return `null` if there are no listeners, this means telemetry related code will not be executed when telemetry is disabled.
2) The `Activity` class from `System.Diagnostics` is a static context, similar to `SynchronizationContext`. This means you can use `ActivitySource.StartActivity` **anywhere**. The `TracerProvider` is something that has to be injected into a service, this heavily limits its possible uses.

The only real benefit is being able to use OpenTelemetry terminology.
