### ISSUE TITLE
Import mods from Vortex if previously used

### ISSUE THREAD

**Issue by RealSourceOfficial** [Nexus-Mods/NexusMods.App#2420]
# Improvement

## Currently 
NexusMods will make the user install mods again, and with Nexus Mods' download speed cap, big mods (such as those for Cyberpunk) take incredibly long to install.

## We want
Instead of making the user re-download mods to restore auto-update functionality, scan for Vortex's database and staging files to determine previously installed mods, where there located, and register them to the game (and library, so that the user can update mods without having to redownload from Nexus Mods by hand)

## Design
Settings menu for importing from previous Vortex install
Hints on where the folders may be, e.g. for users coming from Steamtinkerlaunch's Vortex implementation (such as me)

**Comment by halgari** [comment]
We've discused this in the past, but likely won't be implementing it anytime son. We're focusing on having better behavior in the app by default instead of on building tools for migration that are essentially "one use". Once someone migrates to the app from Vortex they likely won't need to do it again. So there's very little reward for the effort. 

Instead we're recommending that users build a collection from their existing setup and install that into the app.
