### ISSUE TITLE
As an extension developer, I want to set sorting rules

### ISSUE THREAD

**Issue by Aragas** [Nexus-Mods/NexusMods.App#299]
# User story

**As an** extension developer

**I want to** set sorting rules

**So that** the mod list is automatically sorted

The `Mod` class exposes a `SortRules` property that can't be accessed currently.  
One of the more logical methods where the sorting rules could be set is `ValueTask<IEnumerable<ModInstallerResult>> GetModsAsync`, but as a PoC I already tried it before #292 was merged and `SortingRules` could be set, but I had an unresolved issue.  
I need to be able to alias a `ModId` to some arbitrary mod id that the game uses.  
For example, in Bannerlord a mod can have it's own internal Module Id if a `SubModule.xml` (a mod manifest) is present. If it's present, I want to somehow alias this Module Id to a ModId, so I can resolve it from NMA data storage when I parse the manifest file and create the sorting rules. There also is another issue. if, for some reason, the alias is missing (because the mod is not yet parsed by NMA), I won't be able to add the sorting rule. This means that there might be needed a two pass system, when first all aliases are added to the data store, then the sorting rules could be applied.

**Comment by erri120** [comment]
`Mod.SortRules` is not really useable right now. The Bethesda support code is the only place where we employ using, however, this is done to generate the `plugins.txt` file and doesn't use `ModId`.

For now, I'd recommend implementing an `IFileAnalyzer` and a custom `IFileAnalysisData` type that contains dependency information.

**Comment by Aragas** [comment]
> For now, I'd recommend implementing an IFileAnalyzer and a custom IFileAnalysisData type that contains dependency information.

Already done! Waiting then for the abstraction to be ready for use

**Comment by Al12rs** [comment]
Would this be exclusively for game extensions? I'm still not sure about what kind of extensions NMA will support in the future.

How to best handle a case where multiple extensions want to define the order of the mods?
In MO2, extensions can manipulate the priority of mods through an interface, but not to the scope of the ESP list (bethesda plugins), where the game extension has the control and the responsibility of defining the starting order. The ESPList is still exposed to other extensions through an interface, though the initial order is defined by the game extension.

Since the EspList would be a game specific feature it makes sense that the game extension would have full control over it, while mods are a common concept for all games. Mod order might not even be a valid concept for some games. 
So what component would have the responsibility of defining the order of the mods? The game extension? The main application? So while the solution for this issue might be the implementation of an interface that allows the manipulation of the order, it might be worth to better define which component has which responsibility when it comes to defining the order.

**Comment by halgari** [comment]
Done as part of #334

**Comment by Aragas** [comment]
@halgari not sure it's done! I still need ModId aliasing, plus there's no way to set `SortRules` explicitly, as I understand

**Comment by Aragas** [comment]
Oh, sorry, I found `IGeneratedSortRule`. I guess that's the thing to use?

**Comment by Aragas** [comment]
Okay, I was able to implement the custom SortRule, but I'm not able to inject it. I guess `ModInstallerResult` needs a new property for `SortRules`

**Comment by halgari** [comment]
Ah, yep, you're right, we'll need to add that to the ModInstallerResult
classification
