### ISSUE TITLE
As a user, I want to view a loadout

### ISSUE THREAD

**Issue by Greg-Nexus** [Nexus-Mods/NexusMods.App#400]
# User story

**As a** user

**I want to** view my loadout

**So that** I can make changes

## Requirements
Create a new screen to view a loadout, this should display all of the mods and collections within it.

Other issues will build on this, to allow users to easily manage the loadout.

## Design
_(Any designs required for this story)_

## DOD
_(Describe the expected behaviour from the users point of view. Create multiple DoD's if required to fully describe what should happen. Number each DoD)_

## Scenario 1
**Given** _______

**When** _______

**Then** _______

**Comment by Sewer56** [comment]
Assuming the scope of this issue doesn't include recursive functionality (e.g. viewing the contents of a mod inside a loadout), this has probably been achieved, since you can view the mods present in a loadout from both the CLI and GUI.

On the other hand, issues such as:

- https://github.com/Nexus-Mods/NexusMods.App/issues/399
- https://github.com/Nexus-Mods/NexusMods.App/issues/398

Don't currently have any UI implementation, so should probably stay open.

**Comment by Al12rs** [comment]
This can be closed, we can use the other issues for additional functionality
