### ISSUE TITLE
Add the workspace "panel" system to the app and adapt existing panels 

### ISSUE THREAD

**Issue by halgari** [Nexus-Mods/NexusMods.App#409]
The following needs to be done:

* Finish up and PR the existing work for the structure defined in [UI ADR-0001](https://github.com/Nexus-Mods/NexusMods.App/blob/main/docs/decisions/frontend/0001-UI-Panel-Layout.md)
* Build a structure for defining and registering panels via the DI system
* Adapt the existing views to the panel system:
  * Downloads Panels
  * Mods loadout
  * Detected games

**Comment by Al12rs** [comment]
# Converting existing views into Panel Pages:
- [ ] `LoadoutGridView`
- [ ] `MyGamesView` 
- [ ] `InProgressView`
- [ ] `PlaceHolderView` ?

## Details:
To convert into pages we need to define a serializable Context for the page, that can be used by a factory to create the VM of the page, and restore it if necessary.
The context will have to be provided by the code requesting the page to be shown. 
An example is the `LoadoutId` necessary for the `LoadoutGridView` 

### `LoadoutGridView`:
This has already been converted into by @erri120 .
Context only contains the `LoadoutId` that needs to be displayed in the grid.

### `MyGamesView`:
It seems this can obtain all it needs from the ServiceProvider.
It finds everything out using various services that get injected. In particular it gets a list of IGames, which is also injected.
Since the factory will have access to ServiceProvider this view shouldn't have any issues.

Note:  `FoundGamesView` is not actually a `RightContentView` even if the VM is extending that interface for some reason.
`FoundGamesView` is used inside `MyGamesView`, and does not require conversion to a Panel Page.

### `InProgressView`:
Here as well we get away with getting services injected.
It requires the DownloadService and the OverlayController service, can populate itself from that.

### `PlaceHolderView`:
I thought about removing this but it could come in handy and doesn't require any context. 

# Views and navigation that can be removed (they are stubs/not used, will be remade later as panels directly):
- [ ] Download `HistoryView`
- [ ] Download `CompletedView`
- [ ] `HomeView` (currently not used)
- [ ] Newsfeed left menu entry
- [ ] Browse Games left menu entry

**Comment by Al12rs** [comment]
We had a meeting discussing workspaces and some conclusions were extracted:

### Workspace context
Each workspace should be associated to one Loadout, or an empty one (for Choose Game workspace or Global Mod Library). 
It should not allow pages that have another loadout as context. To visualize different loadouts at the same time you will need multiple windows.

Loadouts will be shown in the Spine. Each spine element will have a separate workspace.

The importance of workspace context is evident when considering the "New Tab" page, that shows all the pages that can be opened inside this tab. The workspace needs to know which Loadout should be opened in the Loadout Grid page when the user selects it in the "New Tab" page. 

Mod Library will have it's own workspace where Downloads will also reside. This means that by default they will be global.
They will allow though the user to select a target Loadout, so that they may filter mods by the game of the loadout and automatically add mods to the selected loadout.

Each Loadout specific workspace will have a shortcut to to open in a Page the Downloads and Mod library views, already filtered by the current loadout. This allows Downloads for example to be inside a panel of the loadout workspace, while still having its dedicated workspace for global operations.

### Popped out Panels or Popped out workspaces
Disagreement about whether the popped out window should contain just the Panel or an entire workspace.

Conclusion: 
The way panels were designed does not allow them to live outside a workspace, so the popped out window will have a workspace.
The workspace will be limited to just one panel, but will allow multiple tabs on that panel.

When an interaction would open a new panel in the popped out workspace, the new panel should instead be popped out as a new separate window (inside its own workspace).

The popped out workspace should have the same context as the one that spawned it.
