### ISSUE TITLE
As a user, I want to update the Nexus Mods App

### ISSUE THREAD

**Issue by Greg-Nexus** [Nexus-Mods/NexusMods.App#465]
# User story

**As a** user

**I want to** update to the latest version of the App

**So that** I can benefit from new features, bug fixes and improvements

## Requirements
We'll need to add an update mechanism for users, with a UI interface.

Updating the app should download and install the latest version.

## Design

[Figma design for basic first iteration](https://www.figma.com/file/oWcjirFQDdwyeVPGiCUgWP/%F0%9F%93%B1-Update-application?type=design&node-id=0%3A1&mode=design&t=rWBWMF7SjxGeoB48-1)

![image](https://github.com/Nexus-Mods/NexusMods.App/assets/118466382/6b388a82-6d87-46c6-96c5-5b58332662ea)

## DOD
_(Describe the expected behaviour from the users point of view. Create multiple DoD's if required to fully describe what should happen. Number each DoD)_

## Scenario 1
**Given** that there is an app update available

**When** I start the app

**Then** I see an 'Update available' modal
**And** I see a "[View changelog on GitHub](https://github.com/Nexus-Mods/NexusMods.App/releases)" link

## Scenario 2
**Given** I am viewing the 'Update available' modal

**When** I select "Later"

**Then** the modal closes

## Scenario 3
**Given** I am viewing the 'Update available' modal

**When** I select "Update"

**Then** the app updates to the latest version

**Comment by erri120** [comment]
Things to consider:

- multiple release channels (stable, pre-release)
- multiple release sources (GitHub, AUR, Flathub)
- different update mechanics depending on the type of package (MSIX has somewhat broken auto-update mechanism, AUR, Flathub and other Linux based package management systems have their own update mechanisms)
- possible update issues due to #290
