### ISSUE TITLE
Installer architecture revamp

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#489]
As pointed out by @Al12rs, our current architecture and handling for installers doesn't allow for customizations. This issue tracks possible solutions to this problem.

## Possible Solution: Interface Markers

Proposed by @Al12rs, this would allow `AGame` instances to implement a marker:

```c#
interface MyMarker { }

class MyGame : AGame, MyMarker
```

Generic installers that work on multiple games can check for this interface. We might have an installer that always extract archive files into the game folder, or one of its subdirectories. This is useful for things like SKSE and ENB. We would create an interface `RootDirectoryInstallerCompatible` which our `AGame` instance for Skyrim would implement. This interface could have additional methods like `GetInstallationDirectory` to allow for some configuration.

## Possible Solution: Capabilities using value objects

Proposed by me, @erri120, as an alternative to interface markers. The drawbacks of using interface markers is that you don't know they exist unless you closely follow documentation or have seen the source code. I wrote a plugin for a C# project once that had this exact issue, where you could choose from dozens of interfaces to implement, and you had almost no idea which one to choose.

Instead of using interfaces, we could make use of value objects:

```csharp
[ValueObject<string>]
public readonly struct Capability { }

class MyInstaller
{
    public static readonly Capability RequiredCapability => Capability.From("some-unique-identifier");
}

class MyGame
{
    public readonly Capability[] Capabilities => { MyInstaller.RequiredCapability };
}
```

This has the benefit of allow anything to create a new capability, since it's just a typed-string under the hood. The drawback is that this solution doesn't allow for customization, since you essentially can only have flags.

## Possible Solution: Make the Game call the Installer

Proposed by me, @erri120, as something completely different. Currently, the loadout manager gets all registered `IModInstaller` instances from DI. When you install a mod, the loadout manager calls the `GetPriority` method on every mod installer it knows of, and then proceeds to use the installer that returns the highest priority:

```mermaid
flowchart TD
    LoadoutManager[Loadout Manager]
    ModInstaller1[Mod Installer 1]
    ModInstaller2[Mod Installer 2]
    LoadoutManager --> ModInstaller1
    LoadoutManager --> ModInstaller2
```

The core issue we have is that our game implementation has to supply the mod installer with additional information. So why don't we just call the mod installer from the game instead of the loadout manager?

```mermaid
flowchart TD
    LoadoutManager[Loadout Manager]
    Game[Game]
    ModInstaller1[Mod Installer 1]
    ModInstaller2[Mod Installer 2]
    LoadoutManager --> Game
    Game --> ModInstaller1
    Game --> ModInstaller2
```

This immediately solves all our issues. The loadout manager passes the mod to be installed to the game implementation. The game implementation can then return any mod installer instances it wants:

```csharp
class MyInstaller : IModInstaller
{
  MyInstaller(string outputDirecotry) { }
}

class MyGame : AGame
{
  IEnumerable<IModInstaller> GetInstallers()
  {
    yield return new MyInstaller("data");
  }
}
```

This allows the game implementation to construct and configure the installers however it wants. We can even make use of inheritance to provide "default" installers:

```csharp
abstract class AGame
{
  public IEnumerable<IModInstaller> GetInstallers()
  {
    foreach (var installer in GetInstallersImpl())
    {
      yield return installer;
    }
    yield return DefaultInstaller();
  }

  protected abstract IEnumerable<IModInstaller> GetInstallersImpl();
}
```

Or we can move this into the implementation:

```csharp
abstract class AGame
{
  protected readonly IEnumerable<IModInstaller> DefaultInstallers => new[] { new DefaultInstaller()

  public abstract IEnumerable<IModInstaller> GetInstallers();
}

class MyGame : AGame
{
  public override IEnumerable<IModInstaller> GetInstallers()
  {
    foreach (var installer in base.DefaultInstallers)
    {
      yield return installer;
    }
    yield return MyInstaller();
  }
}
```

**Comment by Al12rs** [comment]
In the third proposed option, new installer objects are created by each game, while they are currently singletons handled by the DI.

We could adapt the solution to using the list of singletons from the DI, but we loose the advantage of configuring the installers with the constructor. Singletons would avoid a lot of installer instantiation on each mod install, while creating new objects could avoid any potential thread safety problem of multiple installations at once.

Some installer don't just want the target folder, they might want two target folders, or they could also want more information specialized information such as a list of valid file extensions for a particular folder level, or a list of valid folder names.
These could be all passed through the installer constructor in case of approach 3, or by using interface defined methods in approach 1 with trait interfaces.

I'm leaning towards trait interfaces myself, as a solution that we could reuse for similar use cases. 
We can hopefully reduce the problem @erri120 mentioned with good documentation, though I ask myself if there isn't a way for the app to compose a list of all interfaces requested by all the available installers. 
This can be done easily for ValueObject solution, but passing around interfaces in a way that is useful seems much harder.
Any insights on this?

**Comment by Al12rs** [comment]
After some discussion we came up with a design that is similar to ValueObjects but replaces them with full fledged objects:

## GameCapabilities:

### Main concept:

GameCapabilities represent common features between games, examples would be: 

- Support for a specific mod Installer
- Support for Plugin order management
- Support for BSA archives
- Support for Archive Invalidation (older bethesda games).
- Support for INI Editor
- etc

Each type of capability would be defined by a different interface/abstract class _[Open Issue: interface or abstract class or virtual class?]_, and these abstractions will need to be exposed by the App to all the extensions.

Capability types can expose methods and functionality useful for the support of the feature, or they could be simple marker types.

Examples of exposed methods:
- GetInstallPathTargets()
- ApplySortingRules()
- GetBSAFileList()
- GetBSALoadOrder()

Each game would have and expose a collection of GameCapability implementations.
Game specific implementations of the capabilities would allow customization and configuration of the capability, for the specific game.
Eg: name of the script extender, list of valid file extensions for Data installation, rules and sorting implementations.

There could be common implementations that can be reused by multiple games (e.g. multiple bethesda games using the same implementations).

The main application or other components (e.g. mod installers) would then be able to query the game for the supported capabilities, and check whether the currently managed game is supporting a specific capability this way.
_[Open Issue: how to identify the capability? By type or by ID?]_
The app or component can then use the obtained capability to get details it needs for the support of the feature.

Examples:
- Main app checks whether game has INIEditing capability, and uses the capability to obtain the paths or the references to those files.
- Fomod installer checks whether the game has FomodSupportCapability and uses the capability to get the target path for the specific game (Data path, vs RootFolder, vs other location).

_[Open Issue: Should capabilities be configured by each game statically by creating new class implementations, or should they be configured dynamically by each game through constructors for example]_

### Reasoning:
The objective is to expose reusable game specific data/logic, without putting everything inside IGame.

This way games that don't use the features don't have to deal with Stub methods about things that aren't relevant to them, and feature specific logic and data can be moved to dedicated classes.

This system will hopefully make extending functionalities of the App easier and minimize the changes needed to various components for each addition:
- Adding a new capability would require:
    - Adding the new capability abstraction in the main app.
    - Adding any capability related logic in either the main app or an extension.
    - Adding capability class implementation for each game supporting it, or a few generic ones.
    - Adding an instance of the capability in the game SupportedCapabilities collection.
    - No changes required to existing interfaces, no changes required to any game not interested in the Capability.
- Adding a new game would require:
    - Implementing AGame class.
    - Add implementation for each Capability the game is interested in.
    - Or reuse existing common capability implementations/subclass them.
    - Add instances of the supported capabilities in their SupportedCapabilities collection.
    - No changes to main app, no changes to other games, no changes to other games or other extensions (installers).
-  Adding an extension (eg: installer) would require:
    - Adding the installer implementation.
    - Either adding a new capability that games need to expose to use the installer.
    - Or use an existing capability if available/possible.
    - No changes to main app, no changes to interfaces, no changes to games, unless it is to add capabilities.
    

This should make adding new games (the most common scenario) the operation that requires the least amount of work/changes (usually just adding implementations of a few classes), so that it can be easy for external developers.



## Moving installers inside games:

As a separate concept that can be applied alongside GameCapabilities, mod installers should be provided by the games.

Currently all the installers are registered as singleton in the DI system, this means that if at one point we will have 50 games and each game implements their own installer, during each mod install, 50 different installers are queried for installation.

To avoid this, the idea is that each game provides a list of (potentially configured) installer instances that it supports.
During mod install, the main app queries the game for the list of installers to use.
The main app the proceeds to use these installer instances to complete the installation instead of using the DI list.

This way only installers that are relevant for the game are used.
Installers don't need to know which games support them, since its the game that decides whether a particular installer is supported or not. 

_[Open_ Issue: should the list of supported mod installers be part of the IGame interface or instead be part of a GameCapability like `ModInstallGameCapability`?]_

**Comment by Al12rs** [comment]
@erri120 when discussing the pros and cons of having the game extend interfaces (some marker ones, but mostly with methods), you said that you were opposed to the idea because you had to extend a system like that in the past and it was not a good experience.

You mentioned having difficulty finding which interfaces you needed to extend among a great number of them.

Assuming this project you mentioned is public, could you link to it? I would like to make sure I understand the problems you faced.

**Comment by erri120** [comment]
> @erri120 when discussing the pros and cons of having the game extend interfaces (some marker ones, but mostly with methods), you said that you were opposed to the idea because you had to extend a system like that in the past and it was not a good experience.
> 
> You mentioned having difficulty finding which interfaces you needed to extend among a great number of them.
> 
> Assuming this project you mentioned is public, could you link to it? I would like to make sure I understand the problems you faced.

Both https://github.com/JosefNemec/Playnite and https://github.com/jellyfin/jellyfin have this issue.

**Comment by Al12rs** [comment]
The main outcome of the meeting yesterday was to move more things to be directly owned by the game (installers and so on).

The main problem with that approach is that a direct binding is created between games and other components:
```mermaid
classDiagram
    class Abstractions
    class Game
    class Extension
    class Application
    Game ..> Abstractions
    Game ..> Extension
    Application ..> Abstractions
    Extension ..> Abstractions
```

Let's say an extension author wants to add a diagnostic check that analyzes the script extender logs of the game to and reports warning found there regarding script extender plugins that failed to load.
This makes sense as an extension, but it requires game specific knowledge to work for Skyrim, SpecialEdition, Fallout4, FNV, such as the name and version of the script extender.

With the proposed method of creating abstractions and implementing them inside the games, this extension author would need to:
- Create a new abstraction like IScriptExtenderLogAnalyzer and put it in the Abstractions project.
- Go into each game that has different behaviour and add a new implementation for his new abstraction.

So to add a simple extension it needs to not only edit the Abstractions project, (even though there is already an interface for diagnostic extensions there), but also edit multiple game projects.

This is not good.

Since ScriptExtender is a common feature that has differences between games, it would make more sense to me to have the game expose an API for the App and other extensions, so that they may be able to obtain all the ScriptExtender specific information through that. This way multiple separate components can reuse the ScriptExtender API.

Now the question is, how can the game expose these extra optional methods?
- Add them to the common IGame interface? 
    - What about games that don't care about this at all? Default implementations but still lots of methods to go through.
    - What if the API is big and complex (PluginSystem, ConflictSystem, etc)? Games become very big classes with lots of complex logic.
- Add them to interfaces that the game class can implement?
    - Problems that @erri120 mentioned above
    - Same problem of Game classes becoming big
 - Add them to interfaces, but don't implement them in the game but rather in a separate object?
    - Better separation of concerns, less clutter in Game class
    - How to pass the implementation to potential users if it's not on the game class itself?
        - IGame exposes a list of implementations for these abstractions. 
        - Users can check if list contains implementation or not.
        - Users can use implementation for their purposes.

**Comment by Al12rs** [comment]
> Both https://github.com/JosefNemec/Playnite and https://github.com/jellyfin/jellyfin have this issue. See https://github.com/jellyfin/jellyfin-plugin-template#4a-implement-interfaces for a great example.

@erri120 So the main problem is that extension authors have a hard time finding all the interfaces that they might need to implement?

Would having all these interfaces in obvious central location such as a folder in the Abstractions project help?
Or is the problem more than just discoverability?
