### ISSUE TITLE
Add EA Desktop & Epic support

### ISSUE THREAD

**Issue by halgari** [Nexus-Mods/NexusMods.App#71]
We currently only support GoG and Steam, for our upcoming game support work we should also support EA and Epic games. The GameFinder library supports these sources already so this is mostly just wiring things up

**Comment by erri120** [comment]
It should be noted that EA Desktop support in GameFinder is experimental at best. My implementation of decrypting the files created by EA Desktop can potentially break with every update of EA Desktop. The files will also become unreadable if the user changes their hardware, due to the composition of the decryption keys (as explained in the [wiki](https://github.com/erri120/GameFinder/wiki/EA-Desktop)).

If everything fails, there are some [alternatives](https://github.com/erri120/GameFinder/wiki/EA-Desktop#alternatives) available. I recommend using a registry fallback, and will probably provide an implementation using the EA Servers in GameFinder at a later date.
