### ISSUE TITLE
Pressing Manage Game does not give UI feedback that App is working

### ISSUE THREAD

**Issue by Greg-Nexus** [Nexus-Mods/NexusMods.App#770]
## Edit (@Al12rs)
Changed this issue to give UI feedback when user manages a game.

## Problem:
Managing a new game requires the app to index the game files, which takes a long time. We need to give users feedback of what is happening.

## Currently 
Using the app to manage a game takes too long, the app seems to be hanging with nothing in the log console.

## We want
Managing a game should much faster, the game should appear in the spine quickly and the user should be able to start managing their loadout.

## Supporting Information

https://github.com/Nexus-Mods/NexusMods.App/assets/100707075/63efd6e2-8935-4865-9d33-06f60e34b5c9

Edit:
# Proposed solutions:

#### Pro:
This would allow switching immediately to the new loadout, where the GameFiles mod could be set to "Installing" with a spinner".
#### Cons:
Apply button needs to be disabled, loadout diagnostics could be broken due to missing game files, some installers need to check the game files and could thus fail to install.
Bad idea to have a loadout in an inconsistent state. We would need to disable too many things.

## 2. Switch to a fake temporary workspace that just shows a big page with the progress
The new loadout only gets added to the loadout registry once all the game files have been indexed and ingested.
No loadout in inconsistent state is added to the registry.
#### Pro:
Immediate feedback on action, no risk of user breaking doing unwanted actions, no need to create a locked view for the loadout grid.
#### Cons:
Some parts of the code that deal with managing a new game might assume that the loadout is present in the registry already. We would be dealing with a loadout ID that isn't marked in the registry yet.
Spine needs to account for fake workspaces
We need a way to switch the fake workspace out with the new one once that is ready.
What happens if the app is closed while it is still preparig the loadout?

**Comment by halgari** [comment]
I did some testing on this over the weekend, and I think the main thing we should focus on with this issue is the lack of feedback to the user. Managing a game requires hashing the game files. On my system I can manage the game mostly at the speed of the underlying storage system. This means that on a NVME 4 drive that hits 5GB/sec managing Skyrim SE takes : 18GB / 5GB/sec = 3.5sec. Likewise for Cyberpunk it's 75GB / 5GBsec or 15sec.

Unfortunately this also means that on a slow HDD, we're looking at 12minutes for the initial management.

All that to say, it's the fact that we need to hash the files that creates the problem here, but if we change the way we detect if the user has modified files, we reduce our ability accurately detect changes the user has made to the game. 

So likely the better route here is to move management to the background: create the loadout, but hash the files in the background. This means the user cannot launch the game until the 12 minutes have passed, but at least they can view the initial loadout.

**Comment by Sewer56** [comment]
I think we also run Ingest when a game is added, meaning that existing files may be getting compressed on first add.  
Improving this aspect will (probably) be done during performance pass in Milestone 4/5, as mentioned in a recent meeting.  

Some things that come to mind that will improve the situation however:

- Move to Single Process App (No more DB locks)
  - On Linux, _this currently slows down indexing to a crawl._
- Switching Ingest Settings for Game Files to [Fast/Random Access](https://nexus-mods.github.io/NexusMods.Archives.Nx/Benchmarks/#fastrandom-access-preset) for Nx might yield a small perf bump in presence of many smaller files.

**Comment by Al12rs** [comment]
Fixed in #1147
